/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.producto;

import vista.VentanaEmergente;
import vista.cliente.*;
import controlador.Navegacion;
import controlador.cliente.AccionCliente;
import controlador.cliente.AccionVistaCliente;
import controlador.cliente.EventoDeMouseCliente;
import controlador.producto.AccionConsultaAutomaticaProducto;
import controlador.producto.AccionProducto;
import controlador.producto.AccionVistaProducto;
import controlador.producto.EventoDeMouseProducto;
import modelo.ManipulaBD;
import modelo.objetos.Cliente;
import modelo.objetos.Producto;

import java.sql.SQLException;
import java.util.List;

import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nizar4790k
 */
public class ProductoForm extends javax.swing.JFrame {

    /**
     * Creates new form ClienteForm
     */
    public ProductoForm() {
        initComponents();
      
        setVisible(true);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        btnAtras.setEnabled(true);
        
        
        
        buttonGroup1.add(radCrear);
        buttonGroup1.add(radActualizar);
        buttonGroup1.add(radEliminar);
        buttonGroup1.add(radConsultar);
      
        btnDale.addActionListener(new AccionProducto(this));
        btnAtras.addActionListener(new Navegacion(this) );      // Poniendo botones a la escucha de los eventos
        radConsultar.addActionListener(new AccionVistaProducto(this));
        radEliminar.addActionListener(new AccionVistaProducto(this));
        radCrear.addActionListener(new AccionVistaProducto(this));
        radActualizar.addActionListener(new AccionVistaProducto(this));
        radCrear.setSelected(true);
        jTable1.addMouseListener(new EventoDeMouseProducto(this));
        
        radEliminar.addActionListener(new AccionConsultaAutomaticaProducto(this));
        radCrear.addActionListener(new AccionConsultaAutomaticaProducto(this));
        radActualizar.addActionListener(new AccionConsultaAutomaticaProducto(this));
        radConsultar.addActionListener(new AccionConsultaAutomaticaProducto(this));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        pnlTitulo = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        pnlCampos = new javax.swing.JPanel();
        pnlDescripcion = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        lblPrecio = new javax.swing.JLabel();
        lblCantidad = new javax.swing.JLabel();
        lblItbis = new javax.swing.JLabel();
        txtPrecio = new javax.swing.JTextField();
        txtTasaITBIS = new javax.swing.JTextField();
        radActualizar = new javax.swing.JRadioButton();
        radCrear = new javax.swing.JRadioButton();
        radEliminar = new javax.swing.JRadioButton();
        btnDale = new javax.swing.JButton();
        spnCantidad = new javax.swing.JSpinner();
        radConsultar = new javax.swing.JRadioButton();
        scrTabla = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnAtras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jLabel1.setText("Producto");
        pnlTitulo.add(jLabel1);

        pnlDescripcion.setText("Nombre");

        lblPrecio.setText("Precio");

        lblCantidad.setText("Cantidad");

        lblItbis.setText("ITBIS(%)");

       

        radActualizar.setText("Actualizar");

        radCrear.setText("Crear ");

        radEliminar.setText("Eliminar");

        btnDale.setText("Dale");

        radConsultar.setText("Consulta Simple");
      

        javax.swing.GroupLayout pnlCamposLayout = new javax.swing.GroupLayout(pnlCampos);
        pnlCampos.setLayout(pnlCamposLayout);
        pnlCamposLayout.setHorizontalGroup(
            pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblPrecio)
                    .addComponent(pnlDescripcion))
                .addGap(43, 43, 43)
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                    .addComponent(txtPrecio))
                .addGap(35, 35, 35)
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblItbis)
                    .addComponent(lblCantidad))
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCamposLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTasaITBIS, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCamposLayout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 3, Short.MAX_VALUE)
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(radCrear, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                    .addComponent(radActualizar, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                .addGap(29, 29, 29)
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCamposLayout.createSequentialGroup()
                        .addComponent(radEliminar, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE)
                        .addGap(46, 46, 46)
                        .addComponent(btnDale, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pnlCamposLayout.createSequentialGroup()
                        .addComponent(radConsultar)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        pnlCamposLayout.setVerticalGroup(
            pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCamposLayout.createSequentialGroup()
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCamposLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(pnlDescripcion)
                            .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblCantidad)
                            .addComponent(spnCantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(radCrear)
                            .addComponent(radEliminar))
                        .addGap(14, 14, 14))
                    .addGroup(pnlCamposLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnDale)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(radActualizar)
                        .addComponent(radConsultar))
                    .addGroup(pnlCamposLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblItbis)
                        .addComponent(txtTasaITBIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lblPrecio)))
                .addContainerGap())
        );

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        scrTabla.setViewportView(jTable1);

        btnAtras.setText("Atras");
        btnAtras.setEnabled(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlTitulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrTabla)
            .addComponent(pnlCampos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(332, 332, 332)
                .addComponent(btnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(pnlTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCampos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrTabla, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnAtras)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public javax.swing.JTable getjTable1() {
		return jTable1;
	}

	private void btnConsultarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConsultarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnConsultarActionPerformed

    private void txtTasaITBISActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTasaITBISActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTasaITBISActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ProductoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ProductoForm().setVisible(true);       }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtras;
    private javax.swing.JButton btnDale;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JRadioButton radConsultar;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblCantidad;
    private javax.swing.JLabel lblItbis;
    private javax.swing.JLabel lblPrecio;
    private javax.swing.JPanel pnlCampos;
    private javax.swing.JLabel pnlDescripcion;
    private javax.swing.JPanel pnlTitulo;
    private javax.swing.JRadioButton radActualizar;
    private javax.swing.JRadioButton radCrear;
    private javax.swing.JRadioButton radEliminar;
    private javax.swing.JScrollPane scrTabla;
    private javax.swing.JSpinner spnCantidad;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTasaITBIS;
    // End of variables declaration//GEN-END:variables


    public int[] getSelectedId() // Obtener el Id de los elementos correspondientes a la fila de la tabla
    {

		int [] selectedRows = getjTable1().getSelectedRows();

		
		int idSeleccionados[] = new int [selectedRows.length];
		
		
		for(int i = 0 ;i<selectedRows.length;i++) {
			idSeleccionados[i]= (int) getjTable1().getModel().getValueAt(i, 0);
			
		}
			
		return idSeleccionados;
	
	}


    public javax.swing.JButton getBtnDale() {
		return btnDale;
	}

	public void txtActivacion(boolean activacion) // Metodo creado para activar o desactivar los campos de textos  simultaneamente.
    {
    	getTxtNombre().setEditable(activacion);   
		getSpnCantidad().setEnabled(activacion);
		getTxtTasaITBIS().setEnabled(activacion);
		getTxtPrecio().setEditable(activacion);    
    
    	}

    	public void vaciarTxt() {
    	getTxtNombre().setText(null);
		getSpnCantidad().setValue(0);;
		getTxtPrecio().setText(null);
		getTxtTasaITBIS().setText(null);
    }
    
    
   
   
   
    
    public boolean camposTextoVacios() 
    {
    		
    		boolean txtNombreisNull = txtNombre.getText().equals("");
    		boolean txtPrecioisNull = txtPrecio.getText().equals("");
    		boolean txtTasaITBISisNull = txtTasaITBIS.getText().equals("");
    	
    		
    		boolean areNull = txtNombreisNull || txtPrecioisNull ||  txtTasaITBISisNull ;
    		
    		if(areNull) {
    		
    		VentanaEmergente.errorEmergente("Asegurese de que no haya campos vacios");
    	
    	
    	}
    		
    		return areNull;
    	
    	
    	
    }
    
    public void rellenarCamposProducto() {
		// TODO Auto-generated method stub

    	int row = getjTable1().getSelectedRow();
		int id = (int) getjTable1().getModel().getValueAt(row, 0);
		
		Producto producto = ManipulaBD.getObject(id, Producto.class);
		
		getTxtNombre().setText(producto.getDescripcion());
		getTxtPrecio().setText(String.valueOf(producto.getPrecio()));
		getTxtTasaITBIS().setText(String.valueOf(producto.getTasaItbis()));
		getSpnCantidad().setValue(producto.getCantidad());
	}
    
    public void rellenarTablaConsulta() 
	{  // rellenar la tabla
		try 
		{
		List<Producto> lista = 	ManipulaBD.<Producto>consultarObjeto(Producto.class);
	
		//String[] columnas = Connection3.getColumnNames(Cliente.class);
		
		DefaultTableModel tblModel = new DefaultTableModel();
		List<String> columnas = (List) ManipulaBD.getColumnNames("producto");
		
		for(String col : columnas) 
		{
		tblModel.addColumn(col);
		}
	
		
		for(Producto e : lista) 
		{
			Object obj [] = {e.getId(),e.getDescripcion(),e.getPrecio(),e.getTasaItbis(),e.getCantidad()};
			
			tblModel.addRow(obj);
		}
		
	    getjTable1().setModel(tblModel);
		
	
		} 
		
		catch (SQLException e) 
		{
	
			// TODO Auto-generated catch block
			e.printStackTrace();
			return;
		}

	}

    
    
    
	public javax.swing.JSpinner getSpnCantidad() 
	{
		return spnCantidad;
	}

	public javax.swing.JTextField getTxtNombre() 
	{
		return txtNombre;
	}

	public javax.swing.JTextField getTxtPrecio() 
	{
		return txtPrecio;
	}

	public javax.swing.JTextField getTxtTasaITBIS() 
	{
		return txtTasaITBIS;
	}

	public javax.swing.JRadioButton getRadActualizar() {
		return radActualizar;
	}

	public javax.swing.JRadioButton getRadCrear() {
		return radCrear;
	}

	public javax.swing.JRadioButton getRadEliminar() {
		return radEliminar;
	}

	public void setRadActualizar(javax.swing.JRadioButton radActualizar) {
		this.radActualizar = radActualizar;
	}

	public void setRadCrear(javax.swing.JRadioButton radCrear) {
		this.radCrear = radCrear;
	}

	public void setRadEliminar(javax.swing.JRadioButton radEliminar) {
		this.radEliminar = radEliminar;
	}

	public javax.swing.JRadioButton getRadConsultar() {
		return radConsultar;
	}
	




}
